CREATE TABLE IF NOT EXISTS serv(
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  extra BLOB  
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS subpay(
  id TEXT NOT NULL,
  payer TEXT NOT NULL,
  token TEXT NOT NULL,
  extra BLOB,
  PRIMARY KEY(id, payer, token)
) WITHOUT ROWID;